// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/diconico07/TomeTracker/pkg/ent/book"
	"github.com/diconico07/TomeTracker/pkg/ent/series"
)

// BookCreate is the builder for creating a Book entity.
type BookCreate struct {
	config
	mutation *BookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *BookCreate) SetTitle(v string) *BookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNumber sets the "number" field.
func (_c *BookCreate) SetNumber(v int) *BookCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *BookCreate) SetURL(v string) *BookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetOwned sets the "owned" field.
func (_c *BookCreate) SetOwned(v bool) *BookCreate {
	_c.mutation.SetOwned(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BookCreate) SetUpdatedAt(v time.Time) *BookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BookCreate) SetNillableUpdatedAt(v *time.Time) *BookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *BookCreate) SetReleasedAt(v time.Time) *BookCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *BookCreate) SetNillableReleasedAt(v *time.Time) *BookCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetSeriesID sets the "series_id" field.
func (_c *BookCreate) SetSeriesID(v int) *BookCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetCover sets the "cover" field.
func (_c *BookCreate) SetCover(v string) *BookCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *BookCreate) SetNillableCover(v *string) *BookCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BookCreate) SetID(v string) *BookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *BookCreate) SetSeries(v *Series) *BookCreate {
	return _c.SetSeriesID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_c *BookCreate) Mutation() *BookMutation {
	return _c.mutation
}

// Save creates the Book in the database.
func (_c *BookCreate) Save(ctx context.Context) (*Book, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookCreate) SaveX(ctx context.Context) *Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := book.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ReleasedAt(); !ok {
		v := book.DefaultReleasedAt()
		_c.mutation.SetReleasedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Book.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Book.number"`)}
	}
	if v, ok := _c.mutation.Number(); ok {
		if err := book.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Book.number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Book.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := book.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Book.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Owned(); !ok {
		return &ValidationError{Name: "owned", err: errors.New(`ent: missing required field "Book.owned"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Book.updated_at"`)}
	}
	if _, ok := _c.mutation.ReleasedAt(); !ok {
		return &ValidationError{Name: "released_at", err: errors.New(`ent: missing required field "Book.released_at"`)}
	}
	if _, ok := _c.mutation.SeriesID(); !ok {
		return &ValidationError{Name: "series_id", err: errors.New(`ent: missing required field "Book.series_id"`)}
	}
	if v, ok := _c.mutation.SeriesID(); ok {
		if err := book.SeriesIDValidator(v); err != nil {
			return &ValidationError{Name: "series_id", err: fmt.Errorf(`ent: validator failed for field "Book.series_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := book.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Book.id": %w`, err)}
		}
	}
	if len(_c.mutation.SeriesIDs()) == 0 {
		return &ValidationError{Name: "series", err: errors.New(`ent: missing required edge "Book.series"`)}
	}
	return nil
}

func (_c *BookCreate) sqlSave(ctx context.Context) (*Book, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Book.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookCreate) createSpec() (*Book, *sqlgraph.CreateSpec) {
	var (
		_node = &Book{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(book.Table, sqlgraph.NewFieldSpec(book.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(book.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Owned(); ok {
		_spec.SetField(book.FieldOwned, field.TypeBool, value)
		_node.Owned = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(book.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.SeriesTable,
			Columns: []string{book.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreate) OnConflict(opts ...sql.ConflictOption) *BookUpsertOne {
	_c.conflict = opts
	return &BookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreate) OnConflictColumns(columns ...string) *BookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertOne{
		create: _c,
	}
}

type (
	// BookUpsertOne is the builder for "upsert"-ing
	//  one Book node.
	BookUpsertOne struct {
		create *BookCreate
	}

	// BookUpsert is the "OnConflict" setter.
	BookUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *BookUpsert) SetTitle(v string) *BookUpsert {
	u.Set(book.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsert) UpdateTitle() *BookUpsert {
	u.SetExcluded(book.FieldTitle)
	return u
}

// SetNumber sets the "number" field.
func (u *BookUpsert) SetNumber(v int) *BookUpsert {
	u.Set(book.FieldNumber, v)
	return u
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *BookUpsert) UpdateNumber() *BookUpsert {
	u.SetExcluded(book.FieldNumber)
	return u
}

// AddNumber adds v to the "number" field.
func (u *BookUpsert) AddNumber(v int) *BookUpsert {
	u.Add(book.FieldNumber, v)
	return u
}

// SetURL sets the "url" field.
func (u *BookUpsert) SetURL(v string) *BookUpsert {
	u.Set(book.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsert) UpdateURL() *BookUpsert {
	u.SetExcluded(book.FieldURL)
	return u
}

// SetOwned sets the "owned" field.
func (u *BookUpsert) SetOwned(v bool) *BookUpsert {
	u.Set(book.FieldOwned, v)
	return u
}

// UpdateOwned sets the "owned" field to the value that was provided on create.
func (u *BookUpsert) UpdateOwned() *BookUpsert {
	u.SetExcluded(book.FieldOwned)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsert) SetUpdatedAt(v time.Time) *BookUpsert {
	u.Set(book.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsert) UpdateUpdatedAt() *BookUpsert {
	u.SetExcluded(book.FieldUpdatedAt)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *BookUpsert) SetReleasedAt(v time.Time) *BookUpsert {
	u.Set(book.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *BookUpsert) UpdateReleasedAt() *BookUpsert {
	u.SetExcluded(book.FieldReleasedAt)
	return u
}

// SetSeriesID sets the "series_id" field.
func (u *BookUpsert) SetSeriesID(v int) *BookUpsert {
	u.Set(book.FieldSeriesID, v)
	return u
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *BookUpsert) UpdateSeriesID() *BookUpsert {
	u.SetExcluded(book.FieldSeriesID)
	return u
}

// SetCover sets the "cover" field.
func (u *BookUpsert) SetCover(v string) *BookUpsert {
	u.Set(book.FieldCover, v)
	return u
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BookUpsert) UpdateCover() *BookUpsert {
	u.SetExcluded(book.FieldCover)
	return u
}

// ClearCover clears the value of the "cover" field.
func (u *BookUpsert) ClearCover() *BookUpsert {
	u.SetNull(book.FieldCover)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(book.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BookUpsertOne) UpdateNewValues() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(book.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BookUpsertOne) Ignore() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertOne) DoNothing() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreate.OnConflict
// documentation for more info.
func (u *BookUpsertOne) Update(set func(*BookUpsert)) *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *BookUpsertOne) SetTitle(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateTitle() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetNumber sets the "number" field.
func (u *BookUpsertOne) SetNumber(v int) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetNumber(v)
	})
}

// AddNumber adds v to the "number" field.
func (u *BookUpsertOne) AddNumber(v int) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.AddNumber(v)
	})
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateNumber() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateNumber()
	})
}

// SetURL sets the "url" field.
func (u *BookUpsertOne) SetURL(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateURL() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateURL()
	})
}

// SetOwned sets the "owned" field.
func (u *BookUpsertOne) SetOwned(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetOwned(v)
	})
}

// UpdateOwned sets the "owned" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateOwned() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateOwned()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsertOne) SetUpdatedAt(v time.Time) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateUpdatedAt() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *BookUpsertOne) SetReleasedAt(v time.Time) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateReleasedAt() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateReleasedAt()
	})
}

// SetSeriesID sets the "series_id" field.
func (u *BookUpsertOne) SetSeriesID(v int) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateSeriesID() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSeriesID()
	})
}

// SetCover sets the "cover" field.
func (u *BookUpsertOne) SetCover(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateCover() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateCover()
	})
}

// ClearCover clears the value of the "cover" field.
func (u *BookUpsertOne) ClearCover() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearCover()
	})
}

// Exec executes the query.
func (u *BookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BookUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BookUpsertOne.ID is not supported by MySQL driver. Use BookUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BookUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BookCreateBulk is the builder for creating many Book entities in bulk.
type BookCreateBulk struct {
	config
	err      error
	builders []*BookCreate
	conflict []sql.ConflictOption
}

// Save creates the Book entities in the database.
func (_c *BookCreateBulk) Save(ctx context.Context) ([]*Book, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Book, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookCreateBulk) SaveX(ctx context.Context) []*Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflict(opts ...sql.ConflictOption) *BookUpsertBulk {
	_c.conflict = opts
	return &BookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflictColumns(columns ...string) *BookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertBulk{
		create: _c,
	}
}

// BookUpsertBulk is the builder for "upsert"-ing
// a bulk of Book nodes.
type BookUpsertBulk struct {
	create *BookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(book.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BookUpsertBulk) UpdateNewValues() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(book.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BookUpsertBulk) Ignore() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertBulk) DoNothing() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreateBulk.OnConflict
// documentation for more info.
func (u *BookUpsertBulk) Update(set func(*BookUpsert)) *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *BookUpsertBulk) SetTitle(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateTitle() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetNumber sets the "number" field.
func (u *BookUpsertBulk) SetNumber(v int) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetNumber(v)
	})
}

// AddNumber adds v to the "number" field.
func (u *BookUpsertBulk) AddNumber(v int) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.AddNumber(v)
	})
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateNumber() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateNumber()
	})
}

// SetURL sets the "url" field.
func (u *BookUpsertBulk) SetURL(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateURL() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateURL()
	})
}

// SetOwned sets the "owned" field.
func (u *BookUpsertBulk) SetOwned(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetOwned(v)
	})
}

// UpdateOwned sets the "owned" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateOwned() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateOwned()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsertBulk) SetUpdatedAt(v time.Time) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateUpdatedAt() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *BookUpsertBulk) SetReleasedAt(v time.Time) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateReleasedAt() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateReleasedAt()
	})
}

// SetSeriesID sets the "series_id" field.
func (u *BookUpsertBulk) SetSeriesID(v int) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateSeriesID() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSeriesID()
	})
}

// SetCover sets the "cover" field.
func (u *BookUpsertBulk) SetCover(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateCover() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateCover()
	})
}

// ClearCover clears the value of the "cover" field.
func (u *BookUpsertBulk) ClearCover() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearCover()
	})
}

// Exec executes the query.
func (u *BookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
