// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/diconico07/TomeTracker/pkg/ent/book"
	"github.com/diconico07/TomeTracker/pkg/ent/predicate"
	"github.com/diconico07/TomeTracker/pkg/ent/series"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *BookUpdate) SetNumber(v int) *BookUpdate {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *BookUpdate) SetNillableNumber(v *int) *BookUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *BookUpdate) AddNumber(v int) *BookUpdate {
	_u.mutation.AddNumber(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *BookUpdate) SetURL(v string) *BookUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetOwned sets the "owned" field.
func (_u *BookUpdate) SetOwned(v bool) *BookUpdate {
	_u.mutation.SetOwned(v)
	return _u
}

// SetNillableOwned sets the "owned" field if the given value is not nil.
func (_u *BookUpdate) SetNillableOwned(v *bool) *BookUpdate {
	if v != nil {
		_u.SetOwned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillableUpdatedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *BookUpdate) SetReleasedAt(v time.Time) *BookUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillableReleasedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *BookUpdate) SetSeriesID(v int) *BookUpdate {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableSeriesID(v *int) *BookUpdate {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdate) SetCover(v string) *BookUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCover(v *string) *BookUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdate) ClearCover() *BookUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *BookUpdate) SetSeries(v *Series) *BookUpdate {
	return _u.SetSeriesID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *BookUpdate) ClearSeries() *BookUpdate {
	_u.mutation.ClearSeries()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Number(); ok {
		if err := book.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Book.number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := book.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Book.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeriesID(); ok {
		if err := book.SeriesIDValidator(v); err != nil {
			return &ValidationError{Name: "series_id", err: fmt.Errorf(`ent: validator failed for field "Book.series_id": %w`, err)}
		}
	}
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.series"`)
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(book.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(book.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owned(); ok {
		_spec.SetField(book.FieldOwned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(book.FieldReleasedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.SeriesTable,
			Columns: []string{book.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.SeriesTable,
			Columns: []string{book.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *BookUpdateOne) SetNumber(v int) *BookUpdateOne {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableNumber(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *BookUpdateOne) AddNumber(v int) *BookUpdateOne {
	_u.mutation.AddNumber(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *BookUpdateOne) SetURL(v string) *BookUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetOwned sets the "owned" field.
func (_u *BookUpdateOne) SetOwned(v bool) *BookUpdateOne {
	_u.mutation.SetOwned(v)
	return _u
}

// SetNillableOwned sets the "owned" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableOwned(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetOwned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableUpdatedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *BookUpdateOne) SetReleasedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableReleasedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *BookUpdateOne) SetSeriesID(v int) *BookUpdateOne {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableSeriesID(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdateOne) SetCover(v string) *BookUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCover(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdateOne) ClearCover() *BookUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *BookUpdateOne) SetSeries(v *Series) *BookUpdateOne {
	return _u.SetSeriesID(v.ID)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *BookUpdateOne) ClearSeries() *BookUpdateOne {
	_u.mutation.ClearSeries()
	return _u
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Number(); ok {
		if err := book.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Book.number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := book.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Book.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeriesID(); ok {
		if err := book.SeriesIDValidator(v); err != nil {
			return &ValidationError{Name: "series_id", err: fmt.Errorf(`ent: validator failed for field "Book.series_id": %w`, err)}
		}
	}
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.series"`)
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(book.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(book.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owned(); ok {
		_spec.SetField(book.FieldOwned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(book.FieldReleasedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.SeriesTable,
			Columns: []string{book.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.SeriesTable,
			Columns: []string{book.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
