// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/diconico07/TomeTracker/pkg/ent/book"
	"github.com/diconico07/TomeTracker/pkg/ent/schema"
	"github.com/diconico07/TomeTracker/pkg/ent/series"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[1].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = bookDescTitle.Validators[0].(func(string) error)
	// bookDescNumber is the schema descriptor for number field.
	bookDescNumber := bookFields[2].Descriptor()
	// book.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	book.NumberValidator = bookDescNumber.Validators[0].(func(int) error)
	// bookDescURL is the schema descriptor for url field.
	bookDescURL := bookFields[3].Descriptor()
	// book.URLValidator is a validator for the "url" field. It is called by the builders before save.
	book.URLValidator = bookDescURL.Validators[0].(func(string) error)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[5].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// bookDescReleasedAt is the schema descriptor for released_at field.
	bookDescReleasedAt := bookFields[6].Descriptor()
	// book.DefaultReleasedAt holds the default value on creation for the released_at field.
	book.DefaultReleasedAt = bookDescReleasedAt.Default.(func() time.Time)
	// bookDescSeriesID is the schema descriptor for series_id field.
	bookDescSeriesID := bookFields[7].Descriptor()
	// book.SeriesIDValidator is a validator for the "series_id" field. It is called by the builders before save.
	book.SeriesIDValidator = bookDescSeriesID.Validators[0].(func(int) error)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.IDValidator is a validator for the "id" field. It is called by the builders before save.
	book.IDValidator = func() func(string) error {
		validators := bookDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	seriesFields := schema.Series{}.Fields()
	_ = seriesFields
	// seriesDescName is the schema descriptor for name field.
	seriesDescName := seriesFields[0].Descriptor()
	// series.NameValidator is a validator for the "name" field. It is called by the builders before save.
	series.NameValidator = seriesDescName.Validators[0].(func(string) error)
	// seriesDescURL is the schema descriptor for url field.
	seriesDescURL := seriesFields[1].Descriptor()
	// series.URLValidator is a validator for the "url" field. It is called by the builders before save.
	series.URLValidator = seriesDescURL.Validators[0].(func(string) error)
}
