// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/diconico07/TomeTracker/pkg/ent/book"
	"github.com/diconico07/TomeTracker/pkg/ent/predicate"
	"github.com/diconico07/TomeTracker/pkg/ent/series"
)

// SeriesUpdate is the builder for updating Series entities.
type SeriesUpdate struct {
	config
	hooks    []Hook
	mutation *SeriesMutation
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdate) Where(ps ...predicate.Series) *SeriesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SeriesUpdate) SetName(v string) *SeriesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableName(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SeriesUpdate) SetURL(v string) *SeriesUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableURL(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *SeriesUpdate) SetAuthor(v string) *SeriesUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableAuthor(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *SeriesUpdate) ClearAuthor() *SeriesUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCover sets the "cover" field.
func (_u *SeriesUpdate) SetCover(v string) *SeriesUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableCover(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *SeriesUpdate) ClearCover() *SeriesUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesUpdate) SetDescription(v string) *SeriesUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableDescription(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SeriesUpdate) ClearDescription() *SeriesUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *SeriesUpdate) AddBookIDs(ids ...string) *SeriesUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *SeriesUpdate) AddBooks(v ...*Book) *SeriesUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdate) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *SeriesUpdate) ClearBooks() *SeriesUpdate {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *SeriesUpdate) RemoveBookIDs(ids ...string) *SeriesUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *SeriesUpdate) RemoveBooks(v ...*Book) *SeriesUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SeriesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SeriesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := series.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Series.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := series.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Series.url": %w`, err)}
		}
	}
	return nil
}

func (_u *SeriesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(series.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(series.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(series.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(series.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(series.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(series.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(series.FieldDescription, field.TypeString)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SeriesUpdateOne is the builder for updating a single Series entity.
type SeriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SeriesMutation
}

// SetName sets the "name" field.
func (_u *SeriesUpdateOne) SetName(v string) *SeriesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableName(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SeriesUpdateOne) SetURL(v string) *SeriesUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableURL(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *SeriesUpdateOne) SetAuthor(v string) *SeriesUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableAuthor(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *SeriesUpdateOne) ClearAuthor() *SeriesUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCover sets the "cover" field.
func (_u *SeriesUpdateOne) SetCover(v string) *SeriesUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableCover(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *SeriesUpdateOne) ClearCover() *SeriesUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesUpdateOne) SetDescription(v string) *SeriesUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableDescription(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SeriesUpdateOne) ClearDescription() *SeriesUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *SeriesUpdateOne) AddBookIDs(ids ...string) *SeriesUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *SeriesUpdateOne) AddBooks(v ...*Book) *SeriesUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdateOne) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *SeriesUpdateOne) ClearBooks() *SeriesUpdateOne {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *SeriesUpdateOne) RemoveBookIDs(ids ...string) *SeriesUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *SeriesUpdateOne) RemoveBooks(v ...*Book) *SeriesUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdateOne) Where(ps ...predicate.Series) *SeriesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SeriesUpdateOne) Select(field string, fields ...string) *SeriesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Series entity.
func (_u *SeriesUpdateOne) Save(ctx context.Context) (*Series, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdateOne) SaveX(ctx context.Context) *Series {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SeriesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := series.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Series.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := series.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Series.url": %w`, err)}
		}
	}
	return nil
}

func (_u *SeriesUpdateOne) sqlSave(ctx context.Context) (_node *Series, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Series.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, series.FieldID)
		for _, f := range fields {
			if !series.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != series.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(series.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(series.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(series.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(series.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(series.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(series.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(series.FieldDescription, field.TypeString)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Series{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
