// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/diconico07/TomeTracker/pkg/ent/book"
	"github.com/diconico07/TomeTracker/pkg/ent/series"
)

// SeriesCreate is the builder for creating a Series entity.
type SeriesCreate struct {
	config
	mutation *SeriesMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SeriesCreate) SetName(v string) *SeriesCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *SeriesCreate) SetURL(v string) *SeriesCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetAuthor sets the "author" field.
func (_c *SeriesCreate) SetAuthor(v string) *SeriesCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableAuthor(v *string) *SeriesCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetCover sets the "cover" field.
func (_c *SeriesCreate) SetCover(v string) *SeriesCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCover(v *string) *SeriesCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SeriesCreate) SetDescription(v string) *SeriesCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableDescription(v *string) *SeriesCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_c *SeriesCreate) AddBookIDs(ids ...string) *SeriesCreate {
	_c.mutation.AddBookIDs(ids...)
	return _c
}

// AddBooks adds the "books" edges to the Book entity.
func (_c *SeriesCreate) AddBooks(v ...*Book) *SeriesCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_c *SeriesCreate) Mutation() *SeriesMutation {
	return _c.mutation
}

// Save creates the Series in the database.
func (_c *SeriesCreate) Save(ctx context.Context) (*Series, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesCreate) SaveX(ctx context.Context) *Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Series.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := series.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Series.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Series.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := series.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Series.url": %w`, err)}
		}
	}
	return nil
}

func (_c *SeriesCreate) sqlSave(ctx context.Context) (*Series, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesCreate) createSpec() (*Series, *sqlgraph.CreateSpec) {
	var (
		_node = &Series{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(series.Table, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(series.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(series.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(series.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(series.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.BooksTable,
			Columns: []string{series.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Series.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesCreate) OnConflict(opts ...sql.ConflictOption) *SeriesUpsertOne {
	_c.conflict = opts
	return &SeriesUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesCreate) OnConflictColumns(columns ...string) *SeriesUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesUpsertOne{
		create: _c,
	}
}

type (
	// SeriesUpsertOne is the builder for "upsert"-ing
	//  one Series node.
	SeriesUpsertOne struct {
		create *SeriesCreate
	}

	// SeriesUpsert is the "OnConflict" setter.
	SeriesUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SeriesUpsert) SetName(v string) *SeriesUpsert {
	u.Set(series.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateName() *SeriesUpsert {
	u.SetExcluded(series.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *SeriesUpsert) SetURL(v string) *SeriesUpsert {
	u.Set(series.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateURL() *SeriesUpsert {
	u.SetExcluded(series.FieldURL)
	return u
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsert) SetAuthor(v string) *SeriesUpsert {
	u.Set(series.FieldAuthor, v)
	return u
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateAuthor() *SeriesUpsert {
	u.SetExcluded(series.FieldAuthor)
	return u
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesUpsert) ClearAuthor() *SeriesUpsert {
	u.SetNull(series.FieldAuthor)
	return u
}

// SetCover sets the "cover" field.
func (u *SeriesUpsert) SetCover(v string) *SeriesUpsert {
	u.Set(series.FieldCover, v)
	return u
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateCover() *SeriesUpsert {
	u.SetExcluded(series.FieldCover)
	return u
}

// ClearCover clears the value of the "cover" field.
func (u *SeriesUpsert) ClearCover() *SeriesUpsert {
	u.SetNull(series.FieldCover)
	return u
}

// SetDescription sets the "description" field.
func (u *SeriesUpsert) SetDescription(v string) *SeriesUpsert {
	u.Set(series.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateDescription() *SeriesUpsert {
	u.SetExcluded(series.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesUpsert) ClearDescription() *SeriesUpsert {
	u.SetNull(series.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SeriesUpsertOne) UpdateNewValues() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SeriesUpsertOne) Ignore() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesUpsertOne) DoNothing() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesCreate.OnConflict
// documentation for more info.
func (u *SeriesUpsertOne) Update(set func(*SeriesUpsert)) *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SeriesUpsertOne) SetName(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateName() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *SeriesUpsertOne) SetURL(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateURL() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateURL()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsertOne) SetAuthor(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateAuthor() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesUpsertOne) ClearAuthor() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearAuthor()
	})
}

// SetCover sets the "cover" field.
func (u *SeriesUpsertOne) SetCover(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateCover() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateCover()
	})
}

// ClearCover clears the value of the "cover" field.
func (u *SeriesUpsertOne) ClearCover() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearCover()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesUpsertOne) SetDescription(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateDescription() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesUpsertOne) ClearDescription() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SeriesUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SeriesUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SeriesUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SeriesCreateBulk is the builder for creating many Series entities in bulk.
type SeriesCreateBulk struct {
	config
	err      error
	builders []*SeriesCreate
	conflict []sql.ConflictOption
}

// Save creates the Series entities in the database.
func (_c *SeriesCreateBulk) Save(ctx context.Context) ([]*Series, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Series, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesCreateBulk) SaveX(ctx context.Context) []*Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Series.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesCreateBulk) OnConflict(opts ...sql.ConflictOption) *SeriesUpsertBulk {
	_c.conflict = opts
	return &SeriesUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesCreateBulk) OnConflictColumns(columns ...string) *SeriesUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesUpsertBulk{
		create: _c,
	}
}

// SeriesUpsertBulk is the builder for "upsert"-ing
// a bulk of Series nodes.
type SeriesUpsertBulk struct {
	create *SeriesCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SeriesUpsertBulk) UpdateNewValues() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SeriesUpsertBulk) Ignore() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesUpsertBulk) DoNothing() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesCreateBulk.OnConflict
// documentation for more info.
func (u *SeriesUpsertBulk) Update(set func(*SeriesUpsert)) *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SeriesUpsertBulk) SetName(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateName() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *SeriesUpsertBulk) SetURL(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateURL() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateURL()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsertBulk) SetAuthor(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateAuthor() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesUpsertBulk) ClearAuthor() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearAuthor()
	})
}

// SetCover sets the "cover" field.
func (u *SeriesUpsertBulk) SetCover(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateCover() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateCover()
	})
}

// ClearCover clears the value of the "cover" field.
func (u *SeriesUpsertBulk) ClearCover() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearCover()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesUpsertBulk) SetDescription(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateDescription() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesUpsertBulk) ClearDescription() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SeriesUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SeriesCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
