// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 13},
		{Name: "title", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt},
		{Name: "url", Type: field.TypeString},
		{Name: "owned", Type: field.TypeBool},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "released_at", Type: field.TypeTime},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "series_id", Type: field.TypeInt},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "books_series_books",
				Columns:    []*schema.Column{BooksColumns[8]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SeriesColumns holds the columns for the "series" table.
	SeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// SeriesTable holds the schema information for the "series" table.
	SeriesTable = &schema.Table{
		Name:       "series",
		Columns:    SeriesColumns,
		PrimaryKey: []*schema.Column{SeriesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		SeriesTable,
	}
)

func init() {
	BooksTable.ForeignKeys[0].RefTable = SeriesTable
	BooksTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(0),
	}
	SeriesTable.Annotation = &entsql.Annotation{
		IncrementStart: func(i int) *int { return &i }(4294967296),
	}
}
